"use client";
import { useState } from "react";
import styles from "./itinerary.module.css";

type Result = { itinerary: { destination: string; status: string; days: Array<{ date: string; dayNumber: number; summary: string; activities: Array<{ id: string; name: string; category: string; description: string; startTime: string | null; endTime: string | null; notes: string; accessibilityNotes: string | null; dietaryNotes: string | null; sourceUrls: string[] }> }> }; research: { mode: string; sessionId: string | null; dashboardUrl: string | null; visitedUrls: string[]; actions: Array<{ at: string; type: string; detail: string; url: string | null }>; candidates: Array<{ id: string; name: string; category: string; description: string; priceLevel: string; estimatedDurationMinutes: number | null; accessibilityNotes: string | null; dietaryNotes: string | null; sourceUrls: string[]; unverifiedFields: string[] }> } };
type State = "idle" | "researching" | "generating" | "saving" | "complete" | "error";

export function ItineraryExperience() {
  const [state, setState] = useState<State>("idle"); const [result, setResult] = useState<Result | null>(null); const [error, setError] = useState<string | null>(null); const [inspector, setInspector] = useState(false);
  const generate = async () => { setError(null); setResult(null); setState("researching"); try { const response = await fetch("/api/itinerary/generate", { method: "POST" }); const payload = await response.json() as Result & { error?: string }; if (!response.ok) throw new Error(payload.error ?? "Generation failed"); setResult(payload); setState("complete"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Generation failed"); setState("error"); } };
  const busy = state === "researching" || state === "generating" || state === "saving";
  return <main className={styles.page}><header><p className={styles.brand}>JAPLAN <span>ITINERARY LAB</span></p><p className={styles.badge}>DEVELOPMENT ONLY</p></header><section className={styles.hero}><p className={styles.eyebrow}>TORONTO · OCT 10—12 · 5 PEOPLE</p><h1>PLAN LESS.<br /><i>GO MORE.</i></h1><p className={styles.intro}>A researched, unvalidated draft that preserves dietary and accessibility uncertainty.</p><button className={styles.generate} onClick={generate} disabled={busy}>{busy ? "JAPLAN IS WORKING…" : "GENERATE ITINERARY ↗"}</button>{state !== "idle" && <p className={styles.status}><span /> {state === "researching" ? "Research and draft generation are running." : state === "complete" ? "Draft saved." : "Generation stopped."}</p>}{error && <div className={styles.error}><b>Couldn’t generate the draft.</b><p>{error}</p><button onClick={generate}>Try again</button></div>}</section>
  {result && <><section className={styles.draft}><div><p className={styles.eyebrow}>STATUS · DRAFT / UNVALIDATED</p><h2>{result.itinerary.destination}</h2></div>{result.itinerary.days.map(day => <article key={day.date} className={styles.day}><p>DAY {day.dayNumber} · {day.date}</p><h3>{day.summary}</h3>{day.activities.map(activity => <div className={styles.stop} key={activity.id}><time>{activity.startTime ?? "TBD"}{activity.endTime ? ` — ${activity.endTime}` : ""}</time><div><b>{activity.name}</b><span>{activity.category}</span><p>{activity.description}</p><small>{activity.notes}</small>{activity.accessibilityNotes && <small>Access: {activity.accessibilityNotes}</small>}{activity.dietaryNotes && <small>Food: {activity.dietaryNotes}</small>}</div></div>)}</article>)}</section><section className={styles.inspector}><button onClick={() => setInspector(value => !value)}>{inspector ? "HIDE" : "SHOW"} RESEARCH INSPECTOR</button>{inspector && <div className={styles.inspectBody}><p>Mode: <b>{result.research.mode}</b></p>{result.research.dashboardUrl && <a href={result.research.dashboardUrl} target="_blank" rel="noreferrer">Open Browserbase session {result.research.sessionId} ↗</a>}<h3>Visited sites</h3>{result.research.visitedUrls.map(url => <a key={url} href={url} target="_blank" rel="noreferrer">{url}</a>)}<h3>Research log</h3>{result.research.actions.map((action, index) => <p key={index}><b>{action.type}</b> · {action.detail}</p>)}<h3>Candidate activity ledger</h3>{result.research.candidates.map(candidate => { const selected = result.itinerary.days.some(day => day.activities.some(activity => activity.id === candidate.id)); return <article key={candidate.id}><p className={selected ? styles.selected : styles.excluded}>{selected ? "SELECTED" : "EXCLUDED"}</p><b>{candidate.name}</b><p>{candidate.description}</p><small>{candidate.priceLevel} · {candidate.estimatedDurationMinutes ? `${candidate.estimatedDurationMinutes} min` : "duration unknown"}</small><small>Access: {candidate.accessibilityNotes ?? "unknown"} · Food: {candidate.dietaryNotes ?? "unknown"}</small><small>Unverified: {candidate.unverifiedFields.join(", ") || "none"}</small>{candidate.sourceUrls.map(url => <a key={url} href={url} target="_blank" rel="noreferrer">Source ↗</a>)}</article>})}</div>}</section></>}
  </main>;
}
